service: job-quest-api
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/prisma/schema-engine-*'

custom:
  appSecrets: ${ssm:/aws/reference/secretsmanager/JobQuestApi}

functions:
  main:
    handler: dist/main.handler
    url: true
    environment:
      DATABASE_URL: ${self:custom.appSecrets.DATABASE_URL}
      JWT_SECRET: ${self:custom.appSecrets.JWT_SECRET}
      JWT_REFRESH_SECRET: ${self:custom.appSecrets.JWT_REFRESH_SECRET}
      ADMIN_REGISTER_KEY: ${self:custom.appSecrets.ADMIN_REGISTER_KEY}
      PRISMA_GENERATE_DATAPROXY: true
      JOB_CREATE_LIMIT: 40
      JOB_LIST_CREATE_LIMIT: 10
